name: "Code Improvement"
description: Create a new ticket for a bug.
title: "[CODE] - <title>"
labels: ["code improvement"]
body:
  - type: input
    id: file
    attributes:
      label: "File Name"
      description: Please enter the name of the file you wish to edit
      placeholder: e.g. StdInp.cs or NavBar.tsx
    validations:
      required: true
  - type: textarea
    id: oldCode
    attributes:
      label: "Old Code"
      description: Please enter the code you wish to replace
  - type: textarea
    id: newcode
    attributes:
      label: "New Code"
      description: Please add the new, improved code you wish to add.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please add a description of the changes made, along with their benefits
    validations:
      required: true