name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - <title>"
labels: ["request"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: Provide addtional information surrounding the feature request
      placeholder: This includes...
    validations:
      required: false
  - type: input
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false